# Generated by Django 5.2.1 on 2025-06-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_core', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional: Upload an image for the menu item.', null=True, upload_to='menu_images/'),
        ),
    ]
